### ISSUE TITLE
Cannot apply migrations

### ISSUE THREAD

**Issue by duikboot** [dnaeon/cl-covid19#1]
Hi,
Thanks for a great project, however I can't run it yet.

I'm trying to run the migrations, but I get the following error:

     [SBCL] CL-USER> (defparameter *db-conn*
                                        (covid19:make-db-conn "covid19.db"))
     [SBCL] CL-USER> (covid19:migrate-db *db-conn*)

> debugger invoked on a SQLITE:SQLITE-ERROR in thread
> #<THREAD "main thread" RUNNING {1000560083}>:
>   Do not know how to pass value (100 0) of type CONS to sqlite.
> Database: covid19.db
> SQL: SELECT * FROM migration ORDER BY id DESC LIMIT ? OFFSET ?
> 
> Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
> 
> restarts (invokable by number or by possibly-abbreviated name):
>   0: [ABORT] Exit debugger, returning to top level.
> 
> (SQLITE:SQLITE-ERROR NIL ("Do not know how to pass value ~A of type ~A to sqlite." (100 0) CONS) :STATEMENT #<SQLITE:SQLITE-STATEMENT {1020CEA863}> :DB-HANDLE NIL :SQL-TEXT NIL)
>    source: (ERROR
>             (IF (EQ ERROR-CODE :CONSTRAINT)
>                 'SQLITE-CONSTRAINT-ERROR
>                 'SQLITE-ERROR)
>             :FORMAT-CONTROL
>             (IF (LISTP MESSAGE)
>                 (FIRST MESSAGE)
>                 MESSAGE)
>             :FORMAT-ARGUMENTS
>             (IF (LISTP MESSAGE)
>                 (REST MESSAGE))
>             :DB-HANDLE DB-HANDLE :ERROR-CODE ERROR-CODE :ERROR-MSG
>             (IF (AND DB-HANDLE ERROR-CODE)
>                 (SQLITE-FFI:SQLITE3-ERRMSG (HANDLE DB-HANDLE)))
>             ...)
> 0] 0

**Comment by dnaeon** [comment]
Hey @duikboot ,

Can you please tell me the following details?

* SBCL version
* OS
* SQLite dev library version

Any chance you are running with an older version of `cl-dbi`?

Just in case can you also update your systems?

``` lisp
CL-USER> (ql:update-dist "quicklisp")
CL-USER> (ql:update-client)
```

I've just tested the `cl-covid19` system on a newly deployed Arch Linux system and it applies migrations fine. Works fine on macOS too here, so will need some more details about your setup and try to reproduce it here as well.

Thanks!

**Comment by duikboot** [comment]
Hi, 

So sorry for wasting your time, updating quicklisp indeed solved my issue.

**Comment by duikboot** [comment]
Thanks again. The project is very impressive.

**Comment by dnaeon** [comment]
No problem, glad to hear you got it working! :)
