### ISSUE TITLE
error trying to create *db-conn*

### ISSUE THREAD

**Issue by JARS3N** [dnaeon/cl-covid19#2]
(defparameter *db-conn*
           (covid19:make-db-conn "covid19.db"))

" the function SQLITE-FFI:SQLITE3-OPEN is undefined:
   [condition of type undefined function]"

**Comment by dnaeon** [comment]
Hey @JARS3N ,

Can you please provide the following details?

* Common Lisp implementation
* OS
* SQLite dev libraries version
* Do you have your Quicklisp dist up-to-date?
* Full backtrace

Thanks!

**Comment by dnaeon** [comment]
Closing this one out, please provide more details if you still experience issues.
