### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [dnaeon/cl-covid19#4]
Building with SBCL 2.2.1.147-31b6a20e3 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 9ea4e2d023dc5d11af6c868c1e16a776a8b6415d

*cl-covid19* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BD0003}>: Component :CL-MIGRATUM.DRIVER.SQL not found, required by #<SYSTEM "cl-covid19">

```

[Full log here](http://report.quicklisp.org/2022-03-22/failure-report/cl-covid19.html)

**Comment by dnaeon** [comment]
Fixed in latest commit.
